#!/usr/bin/env python3
"""Collect values generated by an asynchronous random generator."""

from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """Return the ten random values produced by ``async_generator``."""
    return [number async for number in async_generator()]
